-- Concrete formulas integrated with the existing recipe/POS flow.
-- Run once in Supabase SQL Editor before using the shared multi-device settings.

create table if not exists public.concrete_recipe_settings (
  product_id text primary key,
  truck_capacity_m3 numeric(12,3) not null default 4 check (truck_capacity_m3 > 0),
  charge_empty_space boolean not null default false,
  empty_threshold_m3 numeric(12,3) not null default 0.001 check (empty_threshold_m3 >= 0),
  empty_fee_per_m3 numeric(12,2) not null default 0 check (empty_fee_per_m3 >= 0),
  updated_at timestamptz not null default now(),
  updated_by text
);

create table if not exists public.concrete_delivery_plans (
  id bigint generated by default as identity primary key,
  bill_id text not null,
  product_id text not null,
  product_name text,
  plan_no integer not null check (plan_no > 0),
  total_plans integer not null check (total_plans > 0),
  quantity_m3 numeric(12,3) not null check (quantity_m3 > 0),
  truck_capacity_m3 numeric(12,3) not null check (truck_capacity_m3 > 0),
  empty_m3 numeric(12,3) not null default 0 check (empty_m3 >= 0),
  surcharge numeric(12,2) not null default 0 check (surcharge >= 0),
  request_mix_design boolean not null default false,
  status text not null default 'รอผลิต',
  scheduled_date date,
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  unique (bill_id, product_id, plan_no)
);

create index if not exists concrete_delivery_plans_bill_idx
  on public.concrete_delivery_plans (bill_id, plan_no);
create index if not exists concrete_delivery_plans_status_idx
  on public.concrete_delivery_plans (status, scheduled_date);

alter table public.concrete_recipe_settings enable row level security;
alter table public.concrete_delivery_plans enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'concrete_recipe_settings'
      and policyname = 'concrete_recipe_settings_all'
  ) then
    create policy concrete_recipe_settings_all
      on public.concrete_recipe_settings for all
      using (true) with check (true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'concrete_delivery_plans'
      and policyname = 'concrete_delivery_plans_all'
  ) then
    create policy concrete_delivery_plans_all
      on public.concrete_delivery_plans for all
      using (true) with check (true);
  end if;
end $$;

grant select, insert, update, delete on public.concrete_recipe_settings to anon, authenticated;
grant select, insert, update, delete on public.concrete_delivery_plans to anon, authenticated;
grant usage, select on sequence public.concrete_delivery_plans_id_seq to anon, authenticated;

